Q1. What are the benefits of the built-in array package, if any?

Ans.1 Benefits of the built-in array package are:

* Arrays represent multiple data items of the same type using a single name.

* In arrays, the elements can be accessed randomly by using the index number.

* Arrays allocate memory in contiguous memory locations for all its elements. Hence there is no chance of extra memory being       allocated in case of arrays. This avoids memory overflow or shortage of memory in arrays.

In [2]:
import numpy as np
arr=np.arange(15,30)
arr

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.zeros(12).reshape(3,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Q2. What are some of the array package's limitations?

Ans.2 Some of the array package's limitations
* The number of elements to be stored in an array should be known in advance. 

* An array is a static structure (which means the array is of fixed size). 

* Once declared the size of the array cannot be modified. 

* The memory which is allocated to it cannot be increased or decreased. 

* Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations and the shifting operation is costly. 

* Allocating more memory than the requirement leads to wastage of memory space and less allocation of memory also leads to a problem.

Q3. Describe the main differences between the array and numpy packages.

Ans.3 Main differences between the array and numpy packages are :

* The array package doesn't provide any help with numerical calculation with the items insdie it in number form while NumPy give you a wide variety of numerical operations

* An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.

* In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its column and row index, which makes it slightly time taking. Same goes with appending operation.

* In case of array we do not form a tabular structure, while in numpy it forms a tabular structure

Q4. Explain the distinctions between the empty, ones, and zeros functions.

Ans.4 Below are the distinctions between the empty, ones, and zeros functions :

* empty function: An empty function is a function that does not contain any statement within its body. If you try to write a function definition without any statement in python ,it will return an error. To avoid this, we use pass statement. pass is a special statement in Python that does nothing. It only works as a dummy statement

* ones: This function returns a new array of given shape and data type, where the element’s value is 1.

* zeros: This function returns a new array of given shape and data type, where the element’s value is 0

Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

Ans.5  fromfunction() function construct an array by executing a function over each coordinate and the resulting array, therefore, has a value fn(x, y, z) at coordinate (x, y, z). Parameters : function : [callable] The function is called with N parameters, where N is the rank of shape.

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

Ans.6 If any scaler value such as integer is added to the numpy array then all the elements inside the array will add that value in it.

In [9]:
#Example

import numpy as np

arr=np.arange(12).reshape(4,3)
print(arr)
print()
print(arr+2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

Ans.7 The operation will be done as per operators. Like if we use + operand it will update the current array by adding and when we use '*', it will update by multiplying.

In [10]:
#Example 
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
arr+=2
print(arr)

[[ 4  8 12]
 [16 20 24]
 [28 32 36]
 [40 44 48]]


In [17]:
arr*=2
print(arr)

[[ 8 16 24]
 [32 40 48]
 [56 64 72]
 [80 88 96]]


Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

Ans.8 Yes it is possible that we can include a string of fixed length in numpy array. The datatype of any numpy array containing string values is the maximum length of any string present in the array.

Once lenght is set, it will only be able to store new string having length not more than the maximum length at the time of the creation. If we try to reassign some another string value having length greater than the maximum length of the existing elements, it simply discards all the values beyond the maximum length accept upto those values which are under the limit

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

Ans.9 NumPy's concatenate function can be used to concatenate two arrays either row-wise or column-wise. Concatenate function can take two or more arrays of the same shape and by default it concatenates row-wise i.e. axis=0. The resulting array after row-wise concatenation is of the shape 6 x 3, i.e. 6 rows and 3 columns.  Data type should be same and shape of the two matrices must be same

Q10. What is the best way to use a Boolean array to mask another array?

Ans.10 The best way to use a Boolean array to mask another array is by Using masked_where of numpy package.

In [18]:
x = np.array([True,True,False,True])          
y = np.array([1,2,3,4])         
z = np.ma.masked_where(y>2,x)  
print(list(z))

[True, True, masked, masked]


Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

Ans.11 std() from Numpy package, tstd() from stats package and using pandas with std() can be used to get standard deviation.

In [23]:
a=np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [24]:
np.std(a) #using numpy

14.142135623730951

In [26]:
from scipy import stats
stats.tstd(a)

14.288690166235206

In [27]:
import pandas as pd
pd.Series(a).std()   

14.288690166235206

Q12. What is the dimensionality of a Boolean mask-generated array?

Ans.12 It will remain same elobarated in below example.

In [29]:
y = np.array([True,True,False,True])          
x = np.array([1,2,3,4])         
m = np.ma.masked_where(x>2,y)  
print(list(m))
print()
print('Dimension will be :',m.ndim)

[True, True, masked, masked]

Dimension will be : 1
